T = {
    "cs": {
        "welcome": "Skvele! Pomohu vam sestavit zadani pro vas web. Zabere to 2-3 minuty. Muzete to kdykoli zrusit prikazem /cancel.",
        "ask_name_confirm": "Vase jmeno je <b>{name}</b>?",
        "name_yes": "✅ Ano, to jsem ja",
        "name_change": "✏️ Jine jmeno",
        "ask_name": "Jak se jmenujete? 👤",
        "ask_site_type": "Tesi me, {name}! 🤝\n\nJaky typ webu potrebujete?",
        "site_corp": "🏢 Firemni web",
        "site_landing": "🎯 Landing page",
        "site_eshop": "🛒 E-shop",
        "site_other": "✨ Neco jineho",
        "ask_goal": "Skvele. Jaky je hlavni cil webu?",
        "goal_leads": "🎯 Ziskavat poptavky",
        "goal_sell": "💼 Prodavat sluzby",
        "goal_present": "🏢 Prezentovat firmu",
        "goal_orders": "📦 Prijimat objednavky",
        "goal_other": "✏️ Jine (napsat)",
        "ask_goal_text": "Napiste prosim svuj cil:",
        "ask_pages": "Kolik priblizne stranek by web mel mit?",
        "pages_1": "1 (jednostrankovy)",
        "pages_2_5": "2–5 stranek",
        "pages_5_10": "5–10 stranek",
        "pages_10_plus": "Vice nez 10",
        "pages_unknown": "Zatim nevim",
        "ask_design": "Mate predstavu o designu nebo logo?",
        "design_have": "✅ Mam logo i design",
        "design_need": "🎨 Potrebuji vytvorit",
        "design_inspiration": "💡 Mam jen inspiraci",
        "ask_content": "A texty / fotografie pro web?",
        "content_have": "✅ Vse mam pripravene",
        "content_partial": "📝 Mam castecne",
        "content_need": "❌ Potrebuji pomoc s obsahem",
        "ask_examples": "Muzete poslat odkazy na weby, ktere se vam libi?",
        "skip": "⏭ Preskocit",
        "ask_deadline": "Kdy byste chteli web spustit?",
        "deadline_asap": "🔥 Co nejdrive",
        "deadline_month": "📅 Do mesice",
        "deadline_2_3": "🗓 Za 2–3 mesice",
        "deadline_flex": "🤝 Neni to spech",
        "ask_contact": "Skvele! Jak vas muzeme kontaktovat?",
        "contact_tg": "💬 Telegram (tento)",
        "contact_phone": "📞 Telefon",
        "contact_email": "📧 E-mail",
        "ask_contact_text": "Napiste vas kontakt:",
        "ask_notes": "Chcete dodat neco navic?",
        "notes_no": "✅ Nepotrebuji",
        "notes_yes": "✏️ Ano, napisu",
        "ask_notes_text": "Napiste vase poznamky:",
        "summary_intro": "📋 <b>Zkontrolujte prosim vase zadani:</b>",
        "confirm_send": "✅ Odeslat poptavku",
        "restart": "🔄 Zacit znovu",
        "restarted": "Zaciname od zacatku 🔄",
        "thanks": "🎉 <b>Dekujeme!</b>\n\nVase poptavka byla uspesne odeslana. Ozveme se vam behem <b>24 hodin</b> s navrhem reseni a kalkulaci.",
        "cancelled": "OK, zruseno. Az budete chtit, napiste /start.",
        "sum_name": "Jmeno",
        "sum_site_type": "Typ webu",
        "sum_goal": "Cil",
        "sum_pages": "Stranky",
        "sum_design": "Design",
        "sum_content": "Obsah",
        "sum_examples": "Inspirace",
        "sum_deadline": "Termin",
        "sum_contact": "Kontakt",
        "sum_notes": "Poznamky",
    },
    "en": {
        "welcome": "Great! I'll help you put together a brief for your website. Takes 2-3 minutes. You can cancel anytime with /cancel.",
        "ask_name_confirm": "Your name is <b>{name}</b>?",
        "name_yes": "✅ Yes, that's me",
        "name_change": "✏️ Different name",
        "ask_name": "What's your name? 👤",
        "ask_site_type": "Nice to meet you, {name}! 🤝\n\nWhat type of website do you need?",
        "site_corp": "🏢 Corporate website",
        "site_landing": "🎯 Landing page",
        "site_eshop": "🛒 E-shop",
        "site_other": "✨ Something else",
        "ask_goal": "Got it. What's the main goal of the website?",
        "goal_leads": "🎯 Get leads",
        "goal_sell": "💼 Sell services",
        "goal_present": "🏢 Showcase company",
        "goal_orders": "📦 Take orders",
        "goal_other": "✏️ Other (write)",
        "ask_goal_text": "Please describe your goal:",
        "ask_pages": "Roughly how many pages should the site have?",
        "pages_1": "1 (single page)",
        "pages_2_5": "2–5 pages",
        "pages_5_10": "5–10 pages",
        "pages_10_plus": "More than 10",
        "pages_unknown": "Not sure yet",
        "ask_design": "Do you have a design or logo?",
        "design_have": "✅ I have logo + design",
        "design_need": "🎨 I need it created",
        "design_inspiration": "💡 Only inspiration",
        "ask_content": "What about texts / photos for the site?",
        "content_have": "✅ Everything is ready",
        "content_partial": "📝 Partially ready",
        "content_need": "❌ I need help with content",
        "ask_examples": "Can you share links to websites you like?",
        "skip": "⏭ Skip",
        "ask_deadline": "When would you like to launch?",
        "deadline_asap": "🔥 ASAP",
        "deadline_month": "📅 Within a month",
        "deadline_2_3": "🗓 In 2–3 months",
        "deadline_flex": "🤝 No rush",
        "ask_contact": "Great! How can we contact you?",
        "contact_tg": "💬 Telegram (this one)",
        "contact_phone": "📞 Phone",
        "contact_email": "📧 Email",
        "ask_contact_text": "Write your contact:",
        "ask_notes": "Anything else to add?",
        "notes_no": "✅ Nothing more",
        "notes_yes": "✏️ Yes, I'll write",
        "ask_notes_text": "Write your notes:",
        "summary_intro": "📋 <b>Please review your brief:</b>",
        "confirm_send": "✅ Send request",
        "restart": "🔄 Start over",
        "restarted": "Starting over 🔄",
        "thanks": "🎉 <b>Thank you!</b>\n\nYour request has been sent. We'll get back to you within <b>24 hours</b> with a proposal and estimate.",
        "cancelled": "OK, cancelled. Type /start when ready.",
        "sum_name": "Name",
        "sum_site_type": "Site type",
        "sum_goal": "Goal",
        "sum_pages": "Pages",
        "sum_design": "Design",
        "sum_content": "Content",
        "sum_examples": "Inspiration",
        "sum_deadline": "Deadline",
        "sum_contact": "Contact",
        "sum_notes": "Notes",
    },
    "ru": {
        "welcome": "Отлично! Помогу собрать бриф для вашего сайта. Это займёт 2-3 минуты. Можно прервать командой /cancel.",
        "ask_name_confirm": "Ваше имя <b>{name}</b>?",
        "name_yes": "✅ Да, это я",
        "name_change": "✏️ Другое имя",
        "ask_name": "Как вас зовут? 👤",
        "ask_site_type": "Очень приятно, {name}! 🤝\n\nКакой тип сайта вам нужен?",
        "site_corp": "🏢 Корпоративный сайт",
        "site_landing": "🎯 Лендинг",
        "site_eshop": "🛒 Интернет-магазин",
        "site_other": "✨ Другое",
        "ask_goal": "Хорошо. Какая главная цель сайта?",
        "goal_leads": "🎯 Получать заявки",
        "goal_sell": "💼 Продавать услуги",
        "goal_present": "🏢 Презентовать компанию",
        "goal_orders": "📦 Принимать заказы",
        "goal_other": "✏️ Другое (написать)",
        "ask_goal_text": "Опишите вашу цель:",
        "ask_pages": "Примерно сколько страниц должно быть?",
        "pages_1": "1 (одностраничник)",
        "pages_2_5": "2–5 страниц",
        "pages_5_10": "5–10 страниц",
        "pages_10_plus": "Больше 10",
        "pages_unknown": "Пока не знаю",
        "ask_design": "Есть ли у вас дизайн или логотип?",
        "design_have": "✅ Есть и логотип, и дизайн",
        "design_need": "🎨 Нужно создать",
        "design_inspiration": "💡 Только идеи",
        "ask_content": "А тексты / фото для сайта?",
        "content_have": "✅ Всё готово",
        "content_partial": "📝 Есть частично",
        "content_need": "❌ Нужна помощь с контентом",
        "ask_examples": "Можете прислать ссылки на сайты, которые нравятся?",
        "skip": "⏭ Пропустить",
        "ask_deadline": "Когда хотите запустить сайт?",
        "deadline_asap": "🔥 Как можно скорее",
        "deadline_month": "📅 В течение месяца",
        "deadline_2_3": "🗓 Через 2–3 месяца",
        "deadline_flex": "🤝 Не горит",
        "ask_contact": "Отлично! Как с вами связаться?",
        "contact_tg": "💬 Telegram (этот)",
        "contact_phone": "📞 Телефон",
        "contact_email": "📧 E-mail",
        "ask_contact_text": "Напишите ваш контакт:",
        "ask_notes": "Хотите что-то добавить?",
        "notes_no": "✅ Ничего больше",
        "notes_yes": "✏️ Да, напишу",
        "ask_notes_text": "Напишите ваши заметки:",
        "summary_intro": "📋 <b>Проверьте, пожалуйста, ваш бриф:</b>",
        "confirm_send": "✅ Отправить заявку",
        "restart": "🔄 Начать заново",
        "restarted": "Начинаем сначала 🔄",
        "thanks": "🎉 <b>Спасибо!</b>\n\nВаша заявка отправлена. Свяжемся с вами в течение <b>24 часов</b> с предложением и расчётом.",
        "cancelled": "OK, отменено. Когда захотите — /start.",
        "sum_name": "Имя",
        "sum_site_type": "Тип сайта",
        "sum_goal": "Цель",
        "sum_pages": "Страниц",
        "sum_design": "Дизайн",
        "sum_content": "Контент",
        "sum_examples": "Примеры",
        "sum_deadline": "Срок",
        "sum_contact": "Контакт",
        "sum_notes": "Заметки",
    },
    "uk": {
        "welcome": "Чудово! Допоможу зібрати бриф для вашого сайту. Це займе 2-3 хвилини. Можна зупинити командою /cancel.",
        "ask_name_confirm": "Ваше імʼя <b>{name}</b>?",
        "name_yes": "✅ Так, це я",
        "name_change": "✏️ Інше імʼя",
        "ask_name": "Як вас звати? 👤",
        "ask_site_type": "Дуже приємно, {name}! 🤝\n\nЯкий тип сайту вам потрібен?",
        "site_corp": "🏢 Корпоративний сайт",
        "site_landing": "🎯 Лендинг",
        "site_eshop": "🛒 Інтернет-магазин",
        "site_other": "✨ Інше",
        "ask_goal": "Добре. Яка головна мета сайту?",
        "goal_leads": "🎯 Отримувати заявки",
        "goal_sell": "💼 Продавати послуги",
        "goal_present": "🏢 Презентувати компанію",
        "goal_orders": "📦 Приймати замовлення",
        "goal_other": "✏️ Інше (написати)",
        "ask_goal_text": "Опишіть вашу мету:",
        "ask_pages": "Приблизно скільки сторінок має бути?",
        "pages_1": "1 (односторінковий)",
        "pages_2_5": "2–5 сторінок",
        "pages_5_10": "5–10 сторінок",
        "pages_10_plus": "Більше 10",
        "pages_unknown": "Ще не знаю",
        "ask_design": "Чи є у вас дизайн або логотип?",
        "design_have": "✅ Є і логотип, і дизайн",
        "design_need": "🎨 Потрібно створити",
        "design_inspiration": "💡 Лише ідеї",
        "ask_content": "А тексти / фото для сайту?",
        "content_have": "✅ Все готово",
        "content_partial": "📝 Є частково",
        "content_need": "❌ Потрібна допомога з контентом",
        "ask_examples": "Можете надіслати посилання на сайти, які подобаються?",
        "skip": "⏭ Пропустити",
        "ask_deadline": "Коли хочете запустити сайт?",
        "deadline_asap": "🔥 Якомога швидше",
        "deadline_month": "📅 Протягом місяця",
        "deadline_2_3": "🗓 Через 2–3 місяці",
        "deadline_flex": "🤝 Не горить",
        "ask_contact": "Чудово! Як з вами звʼязатися?",
        "contact_tg": "💬 Telegram (цей)",
        "contact_phone": "📞 Телефон",
        "contact_email": "📧 E-mail",
        "ask_contact_text": "Напишіть ваш контакт:",
        "ask_notes": "Хочете щось додати?",
        "notes_no": "✅ Нічого більше",
        "notes_yes": "✏️ Так, напишу",
        "ask_notes_text": "Напишіть ваші нотатки:",
        "summary_intro": "📋 <b>Перевірте, будь ласка, ваш бриф:</b>",
        "confirm_send": "✅ Надіслати заявку",
        "restart": "🔄 Почати заново",
        "restarted": "Починаємо спочатку 🔄",
        "thanks": "🎉 <b>Дякуємо!</b>\n\nВашу заявку надіслано. Звʼяжемося з вами протягом <b>24 годин</b> з пропозицією та розрахунком.",
        "cancelled": "OK, скасовано. Коли захочете — /start.",
        "sum_name": "Імʼя",
        "sum_site_type": "Тип сайту",
        "sum_goal": "Мета",
        "sum_pages": "Сторінок",
        "sum_design": "Дизайн",
        "sum_content": "Контент",
        "sum_examples": "Приклади",
        "sum_deadline": "Термін",
        "sum_contact": "Контакт",
        "sum_notes": "Нотатки",
    },
}
