"""
Переклади для WebKom Telegram Bot
==================================
Усі тексти, які бачить користувач, на 4 мовах.
"""

T = {
    # ============ ČESKY ============
    "cs": {
        "welcome": "Skvělé! Pomohu vám sestavit zadání pro váš web. Zabere to 2-3 minuty. Můžete to kdykoli zrušit příkazem /cancel.",
        "ask_name": "Jak se jmenujete? 👤",
        "ask_site_type": "Těší mě, {name}! 🤝\n\nJaký typ webu potřebujete?",
        "site_corp": "🏢 Firemní web",
        "site_landing": "🎯 Landing page",
        "site_eshop": "🛒 E-shop",
        "site_other": "✨ Něco jiného",
        "ask_goal": "Skvěle. Jaký je hlavní cíl webu? Co od něj očekáváte?\n\n<i>Například: získávat poptávky, prodávat služby, prezentovat firmu, sbírat objednávky atd.</i>",
        "ask_pages": "Kolik přibližně stránek by web měl mít?",
        "pages_1": "1 (jednostránkový)",
        "pages_2_5": "2–5 stránek",
        "pages_5_10": "5–10 stránek",
        "pages_10_plus": "Více než 10",
        "pages_unknown": "Zatím nevím",
        "ask_design": "Máte představu o designu nebo logo?",
        "design_have": "✅ Mám logo i design",
        "design_need": "🎨 Potřebuji vytvořit",
        "design_inspiration": "💡 Mám jen inspiraci",
        "ask_content": "A texty / fotografie pro web?",
        "content_have": "✅ Vše mám připravené",
        "content_partial": "📝 Mám částečně",
        "content_need": "❌ Potřebuji pomoc s obsahem",
        "ask_examples": "Můžete poslat odkazy na weby, které se vám líbí? (Každý odkaz na novém řádku)\n\nPokud nemáte, klikněte na <b>Přeskočit</b>.",
        "skip": "⏭ Přeskočit",
        "ask_deadline": "Kdy byste chtěli web spustit?",
        "deadline_asap": "🔥 Co nejdříve",
        "deadline_month": "📅 Do měsíce",
        "deadline_2_3": "🗓 Za 2–3 měsíce",
        "deadline_flex": "🤝 Není to spěch",
        "ask_contact": "Skvěle! Jak vás můžeme kontaktovat?\n\n<i>Telefon, e-mail nebo Telegram nick — co preferujete.</i>",
        "ask_notes": "Chcete dodat něco navíc? (Specifika, požadavky, otázky)\n\nNebo klikněte <b>Přeskočit</b>.",
        "summary_intro": "📋 <b>Zkontrolujte prosím vaše zadání:</b>",
        "confirm_send": "✅ Odeslat poptávku",
        "restart": "🔄 Začít znovu",
        "restarted": "Začínáme od začátku 🔄",
        "thanks": "🎉 <b>Děkujeme!</b>\n\nVaše poptávka byla úspěšně odeslána. Ozveme se vám během <b>24 hodin</b> s návrhem řešení a kalkulací.\n\nMezitím nás můžete sledovat na Instagramu nebo napsat na WhatsApp.",
        "cancelled": "OK, zrušeno. Až budete chtít, napište /start.",
        "sum_name": "Jméno",
        "sum_site_type": "Typ webu",
        "sum_goal": "Cíl",
        "sum_pages": "Stránky",
        "sum_design": "Design",
        "sum_content": "Obsah",
        "sum_examples": "Inspirace",
        "sum_deadline": "Termín",
        "sum_contact": "Kontakt",
        "sum_notes": "Poznámky",
    },
    # ============ ENGLISH ============
    "en": {
        "welcome": "Great! I'll help you put together a brief for your website. It takes 2-3 minutes. You can cancel anytime with /cancel.",
        "ask_name": "What's your name? 👤",
        "ask_site_type": "Nice to meet you, {name}! 🤝\n\nWhat type of website do you need?",
        "site_corp": "🏢 Corporate website",
        "site_landing": "🎯 Landing page",
        "site_eshop": "🛒 E-shop",
        "site_other": "✨ Something else",
        "ask_goal": "Got it. What's the main goal of the website? What do you expect from it?\n\n<i>For example: get leads, sell services, showcase the company, take orders, etc.</i>",
        "ask_pages": "Roughly how many pages should the site have?",
        "pages_1": "1 (single page)",
        "pages_2_5": "2–5 pages",
        "pages_5_10": "5–10 pages",
        "pages_10_plus": "More than 10",
        "pages_unknown": "Not sure yet",
        "ask_design": "Do you have a design or logo?",
        "design_have": "✅ I have logo + design",
        "design_need": "🎨 I need it created",
        "design_inspiration": "💡 Only inspiration",
        "ask_content": "What about texts / photos for the site?",
        "content_have": "✅ Everything is ready",
        "content_partial": "📝 Partially ready",
        "content_need": "❌ I need help with content",
        "ask_examples": "Can you share links to websites you like? (One link per line)\n\nIf none, tap <b>Skip</b>.",
        "skip": "⏭ Skip",
        "ask_deadline": "When would you like to launch the site?",
        "deadline_asap": "🔥 ASAP",
        "deadline_month": "📅 Within a month",
        "deadline_2_3": "🗓 In 2–3 months",
        "deadline_flex": "🤝 No rush",
        "ask_contact": "Great! How can we contact you?\n\n<i>Phone, email or Telegram username — whichever you prefer.</i>",
        "ask_notes": "Anything else to add? (Specifics, requirements, questions)\n\nOr tap <b>Skip</b>.",
        "summary_intro": "📋 <b>Please review your brief:</b>",
        "confirm_send": "✅ Send request",
        "restart": "🔄 Start over",
        "restarted": "Starting from the beginning 🔄",
        "thanks": "🎉 <b>Thank you!</b>\n\nYour request has been sent. We'll get back to you within <b>24 hours</b> with a proposed solution and estimate.\n\nIn the meantime, follow us on Instagram or write on WhatsApp.",
        "cancelled": "OK, cancelled. Whenever you're ready, type /start.",
        "sum_name": "Name",
        "sum_site_type": "Site type",
        "sum_goal": "Goal",
        "sum_pages": "Pages",
        "sum_design": "Design",
        "sum_content": "Content",
        "sum_examples": "Inspiration",
        "sum_deadline": "Deadline",
        "sum_contact": "Contact",
        "sum_notes": "Notes",
    },
    # ============ РУССКИЙ ============
    "ru": {
        "welcome": "Отлично! Помогу собрать бриф для вашего сайта. Это займёт 2-3 минуты. Можно прервать в любой момент командой /cancel.",
        "ask_name": "Как вас зовут? 👤",
        "ask_site_type": "Очень приятно, {name}! 🤝\n\nКакой тип сайта вам нужен?",
        "site_corp": "🏢 Корпоративный сайт",
        "site_landing": "🎯 Лендинг",
        "site_eshop": "🛒 Интернет-магазин",
        "site_other": "✨ Другое",
        "ask_goal": "Хорошо. Какая главная цель сайта? Что вы от него ожидаете?\n\n<i>Например: получать заявки, продавать услуги, презентовать компанию, принимать заказы и т. д.</i>",
        "ask_pages": "Примерно сколько страниц должно быть на сайте?",
        "pages_1": "1 (одностраничник)",
        "pages_2_5": "2–5 страниц",
        "pages_5_10": "5–10 страниц",
        "pages_10_plus": "Больше 10",
        "pages_unknown": "Пока не знаю",
        "ask_design": "Есть ли у вас дизайн или логотип?",
        "design_have": "✅ Есть и логотип, и дизайн",
        "design_need": "🎨 Нужно создать",
        "design_inspiration": "💡 Только идеи",
        "ask_content": "А тексты / фотографии для сайта?",
        "content_have": "✅ Всё готово",
        "content_partial": "📝 Есть частично",
        "content_need": "❌ Нужна помощь с контентом",
        "ask_examples": "Можете прислать ссылки на сайты, которые нравятся? (По одной на строку)\n\nЕсли нет — нажмите <b>Пропустить</b>.",
        "skip": "⏭ Пропустить",
        "ask_deadline": "Когда хотите запустить сайт?",
        "deadline_asap": "🔥 Как можно скорее",
        "deadline_month": "📅 В течение месяца",
        "deadline_2_3": "🗓 Через 2–3 месяца",
        "deadline_flex": "🤝 Не горит",
        "ask_contact": "Отлично! Как с вами связаться?\n\n<i>Телефон, e-mail или ник в Telegram — как удобнее.</i>",
        "ask_notes": "Хотите что-то добавить? (Особенности, требования, вопросы)\n\nИли нажмите <b>Пропустить</b>.",
        "summary_intro": "📋 <b>Проверьте, пожалуйста, ваш бриф:</b>",
        "confirm_send": "✅ Отправить заявку",
        "restart": "🔄 Начать заново",
        "restarted": "Начинаем сначала 🔄",
        "thanks": "🎉 <b>Спасибо!</b>\n\nВаша заявка отправлена. Свяжемся с вами в течение <b>24 часов</b> с предложением и расчётом.\n\nА пока — подпишитесь на Instagram или напишите в WhatsApp.",
        "cancelled": "OK, отменено. Как захотите — напишите /start.",
        "sum_name": "Имя",
        "sum_site_type": "Тип сайта",
        "sum_goal": "Цель",
        "sum_pages": "Страниц",
        "sum_design": "Дизайн",
        "sum_content": "Контент",
        "sum_examples": "Примеры",
        "sum_deadline": "Срок",
        "sum_contact": "Контакт",
        "sum_notes": "Заметки",
    },
    # ============ УКРАЇНСЬКА ============
    "uk": {
        "welcome": "Чудово! Допоможу зібрати бриф для вашого сайту. Це займе 2-3 хвилини. Можна зупинити будь-коли командою /cancel.",
        "ask_name": "Як вас звати? 👤",
        "ask_site_type": "Дуже приємно, {name}! 🤝\n\nЯкий тип сайту вам потрібен?",
        "site_corp": "🏢 Корпоративний сайт",
        "site_landing": "🎯 Лендинг",
        "site_eshop": "🛒 Інтернет-магазин",
        "site_other": "✨ Інше",
        "ask_goal": "Добре. Яка головна мета сайту? Що ви від нього очікуєте?\n\n<i>Наприклад: отримувати заявки, продавати послуги, презентувати компанію, приймати замовлення тощо.</i>",
        "ask_pages": "Приблизно скільки сторінок має бути на сайті?",
        "pages_1": "1 (односторінковий)",
        "pages_2_5": "2–5 сторінок",
        "pages_5_10": "5–10 сторінок",
        "pages_10_plus": "Більше 10",
        "pages_unknown": "Ще не знаю",
        "ask_design": "Чи є у вас дизайн або логотип?",
        "design_have": "✅ Є і логотип, і дизайн",
        "design_need": "🎨 Потрібно створити",
        "design_inspiration": "💡 Лише ідеї",
        "ask_content": "А тексти / фотографії для сайту?",
        "content_have": "✅ Все готово",
        "content_partial": "📝 Є частково",
        "content_need": "❌ Потрібна допомога з контентом",
        "ask_examples": "Можете надіслати посилання на сайти, які вам подобаються? (По одному на рядок)\n\nЯкщо ні — натисніть <b>Пропустити</b>.",
        "skip": "⏭ Пропустити",
        "ask_deadline": "Коли хочете запустити сайт?",
        "deadline_asap": "🔥 Якомога швидше",
        "deadline_month": "📅 Протягом місяця",
        "deadline_2_3": "🗓 Через 2–3 місяці",
        "deadline_flex": "🤝 Не горить",
        "ask_contact": "Чудово! Як з вами звʼязатися?\n\n<i>Телефон, e-mail або нік у Telegram — як зручніше.</i>",
        "ask_notes": "Хочете щось додати? (Особливості, вимоги, питання)\n\nАбо натисніть <b>Пропустити</b>.",
        "summary_intro": "📋 <b>Перевірте, будь ласка, ваш бриф:</b>",
        "confirm_send": "✅ Надіслати заявку",
        "restart": "🔄 Почати заново",
        "restarted": "Починаємо спочатку 🔄",
        "thanks": "🎉 <b>Дякуємо!</b>\n\nВашу заявку надіслано. Звʼяжемося з вами протягом <b>24 годин</b> із пропозицією та розрахунком.\n\nА поки — підпишіться на Instagram або напишіть у WhatsApp.",
        "cancelled": "OK, скасовано. Коли захочете — напишіть /start.",
        "sum_name": "Імʼя",
        "sum_site_type": "Тип сайту",
        "sum_goal": "Мета",
        "sum_pages": "Сторінок",
        "sum_design": "Дизайн",
        "sum_content": "Контент",
        "sum_examples": "Приклади",
        "sum_deadline": "Термін",
        "sum_contact": "Контакт",
        "sum_notes": "Нотатки",
    },
}
